### ISSUE TITLE
npm ERR! Error: version not found: md5hex : exponent/md5hex

### ISSUE THREAD

**Issue by sulliwane** [exponentjs/exponent-host#1]
Hello, 

here is the error installing exp with npm from my Ubuntu 14.04. Do you have any idea? thank you.

root@victor-ss9:/home/victor# npm install -g exp
npm http GET https://registry.npmjs.org/exp
npm http 304 https://registry.npmjs.org/exp
npm http GET https://registry.npmjs.org/exponent/json-file
npm http GET https://registry.npmjs.org/exponent/network
npm http GET https://registry.npmjs.org/exponent/md5hex
npm http GET https://registry.npmjs.org/exponent/simple-spinner
npm http GET https://registry.npmjs.org/exponent/spawn-async
npm http GET https://registry.npmjs.org/ccheever/crayon
npm http GET https://registry.npmjs.org/babel-runtime
npm http GET https://registry.npmjs.org/delay-async
npm http GET https://registry.npmjs.org/co
npm http GET https://registry.npmjs.org/freeport-async
npm http GET https://registry.npmjs.org/has-yield
npm http GET https://registry.npmjs.org/inquirer-async
npm http GET https://registry.npmjs.org/inquirer
npm http GET https://registry.npmjs.org/lodash-node
npm http GET https://registry.npmjs.org/instapromise
npm http GET https://registry.npmjs.org/minimist
npm http GET https://registry.npmjs.org/ngrok
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/node-libs-browser
npm http GET https://registry.npmjs.org/qrcode-terminal
npm http GET https://registry.npmjs.org/react
npm http GET https://registry.npmjs.org/react-native
npm http GET https://registry.npmjs.org/pm2
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/simctl/0.0.6
npm http GET https://registry.npmjs.org/window-size
npm http GET https://registry.npmjs.org/wordwrap
npm http 404 https://registry.npmjs.org/exponent/md5hex
npm http 404 https://registry.npmjs.org/exponent/json-file
npm ERR! Error: version not found: md5hex : exponent/md5hex
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/lib/nodejs/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/index.js:896:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/lib/nodejs/request/index.js:847:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.16.0-40-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "exp"
npm ERR! cwd /home/victor
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm http 404 https://registry.npmjs.org/exponent/network
npm http 404 https://registry.npmjs.org/exponent/simple-spinner
npm http 404 https://registry.npmjs.org/exponent/spawn-async
npm http 304 https://registry.npmjs.org/babel-runtime
npm http 404 https://registry.npmjs.org/ccheever/crayon
npm http 304 https://registry.npmjs.org/delay-async
npm http 304 https://registry.npmjs.org/co
npm http 304 https://registry.npmjs.org/freeport-async
npm http 304 https://registry.npmjs.org/has-yield
npm http 304 https://registry.npmjs.org/inquirer-async
npm http 304 https://registry.npmjs.org/inquirer
npm http 304 https://registry.npmjs.org/lodash-node
npm http 304 https://registry.npmjs.org/minimist
npm http 304 https://registry.npmjs.org/instapromise
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/ngrok
npm http 304 https://registry.npmjs.org/node-libs-browser
npm http 304 https://registry.npmjs.org/react
npm http 304 https://registry.npmjs.org/qrcode-terminal
npm http 304 https://registry.npmjs.org/react-native
npm http 304 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/pm2
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/window-size
npm http 304 https://registry.npmjs.org/simctl/0.0.6
npm http 304 https://registry.npmjs.org/wordwrap
npm ERR! Failed resolving git HEAD (git://github.com/ide/react-native) fatal: ambiguous argument 'exp-2015-05-30': unknown revision or path not in the working tree.
npm ERR! Failed resolving git HEAD (git://github.com/ide/react-native) Use '--' to separate paths from revisions, like this:
npm ERR! Failed resolving git HEAD (git://github.com/ide/react-native) 'git <command> [<revision>...] -- [<file>...]'
npm ERR! Failed resolving git HEAD (git://github.com/ide/react-native) 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/victor/npm-debug.log
npm ERR! not ok code 0

**Comment by ide** [comment]
Hi @sulliwane, can you tell me what version of Node you're using? We support only io.js 1.x and up (io.js 2.x preferred), which could fix this issue for you. Our preferred way of installing Node/io.js is with https://github.com/creationix/nvm if you don't have that set up already.

**Comment by sulliwane** [comment]
Hi @ide , thanks for your answer. Here is the version I use
$ nodejs -v
v0.12.4
$ npm -v
2.10.1
I would be surprise this is the problem as they are the latest version. I will try with nvm...

**Comment by ide** [comment]
We don't support legacy Node (specifically because it ships with an old release of V8). The version of npm that ships with io.js also supports the new `@user/package` syntax for dependencies that we use.

**Comment by sulliwane** [comment]
ok, i will try with io.js then...thanks.

**Comment by sulliwane** [comment]
Now that I'm using nmv, it works perfect...many thanks!

**Comment by ide** [comment]
nvm is awesome!
